export {
    QUERIES,
    COLORS,
    FONTS,
    Container,
    Heading,
    MediumHeading,
    SmallHeading,
    Paragraph,
    Inner,
    ParallaxBox,
    CenterBox,
    BtnWrapper,
    BottomBox,
    Options,
    OptionsLink,
    TrackBallSlide,
    ColorSlide,
    NudgeMouse,
    FaqAnimation
} from './styles';
